version: "3"

services:
  api:
    build: ./
    container_name: car_shop
    platform: linux/x86_64
    working_dir: /app
    command: npm start
    restart: always
    depends_on:
      - db
    ports:
      - 3001:3001
    environment:
      - MONGO_URI=mongodb://db:27017/CarShop

  db:
    container_name: car_shop_db
    image: mongo:5.0.7
    platform: linux/x86_64
    restart: always
    ports:
      - 27017:27017

networks:
  default:
    name: car_shop_net

