version: "3"

services:
  api:
    container_name: car_shop
    build: .
    tty: true
    stdin_open: true
    command: bash
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - db
    ports:
      - 3001:3001
    environment:
      - MONGO_URI=mongodb://db:27017/CarShop

  db:
    container_name: car_shop_db
    image: mongo:5.0.7
    restart: always
    ports:
      - 27017:27017

networks:
  default:
    name: car_shop_net

